### ISSUE TITLE
Translate level names

### ISSUE THREAD

**Issue by tigertv** [jubalh/nudoku#15]
Translate level names in difficulty_to_str(DIFFICULTY level), ie. easy, hard, normal in german, spanish, and russian.

**Comment by jubalh** [comment]
The person who contributed the first translation also had this idea.
At that time I commented on the PR that I would prefer having it in english.

I think all the commandline switches and parameters should stay the same independent of the language being used.

**Comment by tigertv** [comment]
No. It's not command line params. It's in the gameplay, file sudoku.c . The levels are shown in right side of the screen.

```
char* difficulty_to_str(DIFFICULTY level)
{
	switch(level)
	{
		case D_HARD:
			return "hard";
		case D_NORMAL:
			return "normal";
		case D_EASY:
		default:
			return "easy";
	}
}
```

I suppose it must be like that 

```
char* difficulty_to_str(DIFFICULTY level)
{
	switch(level)
	{
		case D_HARD:
			return _("hard");
		case D_NORMAL:
			return _("normal");
		case D_EASY:
		default:
			return _("easy");
	}
}
```

**Comment by jubalh** [comment]
Yes, you are right :)
PR welcome.

**Comment by tigertv** [comment]
:) Done.
