### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by absolutelynothelix** [jubalh/nudoku#30]
hello, i would like to see a way to disable filling background with color and leave it transparent, so i will see either my terminal background or things behind it if terminal itself is transparent, because on some terminal palette configurations the game could look weird or inconvenient for playing:
![rip background](https://user-images.githubusercontent.com/52252283/62237716-2bc3b780-b3da-11e9-8976-c79664d60285.png)

also would be good to see this as default behavior

**Comment by absolutelynothelix** [comment]
talking about colors... would be good to make internal grid of squares gray or black instead, because green is not very convenient and i already confused some squares and thought that my layout is broken

**Comment by jubalh** [comment]
> talking about colors... would be good to make internal grid of squares gray or black instead, because green is not very convenient and i already confused some squares and thought that my layout is broken

I think grey is much harder to differentiate on a black background then green. I think it looks good this way. I'm not sure what you mean about confusing squares. Why would the green color be more confusing than grey?
