### ISSUE TITLE
My eyes are bleeding

### ISSUE THREAD

**Issue by ulfgebhardt** [jubalh/nudoku#33]
![image](https://user-images.githubusercontent.com/1238238/62801324-cb253080-bae5-11e9-8889-ddda2d498ad1.png)

In Fish shell the difference between the line colors are to small (green, blue). Therefore it is hard to determine if a square is part of the blue 9x9 field.

Suggestion:
- Use different linestrength for blue and green lines (e.g make green ones dotted)
- Change colors a bit

**Comment by jubalh** [comment]
I can read it just fine.
