### ISSUE TITLE
Make difficulty adjustable ingame

### ISSUE THREAD

**Issue by ulfgebhardt** [jubalh/nudoku#34]
The difficulty setting can only be set when starting the game. This is quite an inconvenience.

Suggestion:
- Make a keybind to set the difficulty
- Since this will take effect on the next puzzle only inform the user

`Niveau: hard (next will be easy)`

When there is no change in difficulty the current behaviour should remain:

`Niveau: hard`

**Comment by jubalh** [comment]
Just restart ;)
