### ISSUE TITLE
Pressing random keys makes the program quit

### ISSUE THREAD

**Issue by ulfgebhardt** [jubalh/nudoku#35]
The program ends when pressing following keys/combos (in fish shell)
- shift + q (documented)
- ctrl + q (thats cool and not documented)
- ctrl + c (also cool not documented either)
- mod + q
- insert (numlock)
- ctrl + insert
- mod + insert
- f2
- f3
- f4
- f5
- shift + del
- ctrl + del
- mod + del
- ctrl + page down
- mod + page down
- ctrl + page up
- mod + page up
- ctrl + del (numlock)
- mod + del (numlock)
- del (numlock)
- enter (numlock)
- ctrl + enter (numlock)
- mod + enter (numlock)
- mod + enter
- mod + % (numlock)
- mod + * (numlock)
- mod + - (numlock)
- ...
- and many more

Why the f*ck does the program exit with anything else then the usual ctrl + q or ctrl + c?

This is very awesome when you use arrow keys to navigate and your keyboard has `insert` next to the right arrow key... </3

Also:
- Numlock numbers do not work whatever state the numlock is in does not matter
- h,j,k,l are in a line on my keyboard (qwer layout). They are not made for navigating
- arrow keys work for navigating but are not documented
- w,a,s,d are not working tho this is classified as a game....

If the reason for this behaviour is my fish shell please make keybinds adjustable.

<3

**Comment by ginsburgnm** [comment]
> h,j,k,l are in a line on my keyboard (qwer layout). They are not made for navigating

They are made for navigating. See: vim, ranger, less, zathura, cmus, mutt, w3m, tmux and countless other curses-based tools. Which this is a curses based program, so it makes sense for the author to have utilized a common practice.

> arrow keys work for navigating but are not documented
h, j, k, l are historically arrow keys so it makes sense that arrows keys also work.

for more information: https://catonmat.net/why-vim-uses-hjkl-as-arrow-keys

> w,a,s,d are not working tho this is classified as a game....

They shouldn't


As for the rest ¯\_(ツ)_/¯

**Comment by jubalh** [comment]
> Why the f*ck does the program exit with anything else then the usual ctrl + q or ctrl + c?

For me it doesn't. Though you forgot to mention `Q`.

> w,a,s,d are not working tho this is classified as a game....

lol?
