### ISSUE TITLE
Cannot build last commit

### ISSUE THREAD

**Issue by BachoSeven** [jubalh/nudoku#39]
Hi, I was trying out this game and wanted to update the outdated AUR package. In doing so I tried to build the latest master, and failed for some formatting-related error which
must be related to the latest japanese-locale commits, although I couldn't figure out the reason for the error more specifically:
``` sh
rm -f ja.gmo && /usr/bin/msgmerge --for-msgfmt -o ja.1po ja.po nudoku.pot && /usr/bin/msgfmt -c --statistics --verbose
-o ja.gmo ja.1po && rm -f ja.1po
ja.1po:49: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
/usr/bin/msgfmt: found 1 fatal error
ja.1po: 33 translated messages.
make[2]: *** [Makefile:157: ja.gmo] Error 1
make[1]: *** [Makefile:198: stamp-po] Error 2
make: *** [Makefile:442: all-recursive] Error 1
```

Thanks in advance!

EDIT: Although my terminal cannot show japanese, I suspect that the problem is with the `%s` and `%d` arguments on line 49 of ja.1po being swapped in `msgstr` with respect to `msgid`.
I would guess this is because of the phrasing in the translation, but perhaps it is a problem for `msgfmt`..

**Comment by jubalh** [comment]
@BachoSeven thanks for reporting!

I thought I build it before merging, maybe not true :/

Will try to look at it soon. @cmplstofB do you have time to check this?

**Comment by cmplstofB** [comment]
I’m very sorry... I have fixed `ja.po` file.
It will probably work.

---

Off topic, but the [`nudoku.pot` file](https://github.com/jubalh/nudoku/blob/a8299b1a6035f1c220288b8f159dd7fe56ea1103/po/nudoku.pot) seems to be a bit old.
It doesn't generate a translation for the “Output PNG” (-p) option and so on.

**Comment by jubalh** [comment]
> It doesn't generate a translation for the “Output PNG” (-p) option and so on.

Yes that's possible. I added this later and then maybe forgot to update the pot file.
If you want you can create another PR that adds it.

@BachoSeven the build succeeds now after merging the fix from @cmplstofB in https://github.com/jubalh/nudoku/pull/40. Can you confirm/close this issue?

**Comment by BachoSeven** [comment]
Yes, it builds correctly.

Thank you both @jubalh @cmplstofB for the quick response. Now I can finish packaging this for the AUR :)

**Comment by jubalh** [comment]
Thanks guys!
