### ISSUE TITLE
Game is unwinable

### ISSUE THREAD

**Issue by retrofitter** [jubalh/nudoku#4]
Game has same numbers in rows, columns and 3x3 squares.

**Comment by jubalh** [comment]
Which OS/Distribution?
Which compiler?
Does this happen right after starting, after generating a new sudoku, after you filled in one number or after you requested a hint?

**Comment by retrofitter** [comment]
Linux/Arch i686
gcc???
0.2.3-4-gb2dbfe5
Error occurs when starting a new game and after asking for a New Puzzle.
![2015-08-25-183122_1024x768_scrot](https://cloud.githubusercontent.com/assets/13805912/9488758/f177cae0-4b90-11e5-8395-a07b350b2db6.png)

**Comment by jubalh** [comment]
Did you finish the first game? Or pressed 'N' to require a new game directly?

For reference:
So the stream is: 5..2.4.96.711697.54287...425.964.28319...5.142...129..8...835.97.25263719..9..4.8

nudoku -s 5..2.4.96.711697.54287...425.964.28319...5.142...129..8...835.97.25263719..9..4.8
Notices about a wrong string. So this works. Error must lie somewhere else. Further digging.

**Comment by retrofitter** [comment]
I just pressed 'N' after starting. When I press 'S' it says "Solved" but does not fill in. Changing difficulty does not change anything. Also when I press 'H' nothing happens.

**Comment by jubalh** [comment]
I hope this fixes it. Please test and let me know.

**Comment by retrofitter** [comment]
Problem fixed. Game can be beat and keys 'c,N,S,H' all work thank you.

**Comment by jubalh** [comment]
Thanks for reporting!

**Comment by jubalh** [comment]
@atdi4ever since you run arch: do you might want to create a package for AUR? :)
