### ISSUE TITLE
Allow pausing game

### ISSUE THREAD

**Issue by sohang3112** [jubalh/nudoku#47]
# Feature Request

Allow pausing the game (i.e., saving the current state of the game somewhere) and quitting. The next time `nudoku` starts, either the paused game can be resumed, or a new game can be played.

**Comment by jubalh** [comment]
Sounds like a fun task.

However I don't plan to add this myself.

**Comment by dogukanteber** [comment]
This seems interesting. I will work on this issue. I am thinking to keep the current state in a file but I do not know where to store that file.

Is it okay if I store the current state in a file? If yes, where can I keep that file? If keeping the current state in a file is not okay, how can I store that data?

**Comment by sohang3112** [comment]
Saving state in a file should be OK - maybe create a file like `~/.nudoku/saved_game`?

**Comment by jubalh** [comment]
Yep. $XDG_DATA_HOME should be the place.
