### ISSUE TITLE
some bugs in the man page

### ISSUE THREAD

**Issue by agaida** [jubalh/nudoku#5]
W: nudoku: manpage-section-mismatch usr/share/man/man1/nudoku.1.gz:2 1 != 08 August 2015
W: nudoku: manpage-has-errors-from-man usr/share/man/man1/nudoku.1.gz 54: warning [p 1, 9.0i]: cannot adjust line

**Comment by jubalh** [comment]
Thanks for that!
I fixed the first one, but getting rid of the second one would mean to remove the example string I guess. I only included it because some users didn't understand it without the example. Since it's just a warning I guess the second one will have to stay.
