### ISSUE TITLE
Ambiguous games are generated

### ISSUE THREAD

**Issue by victorz** [jubalh/nudoku#50]
Games like this can be generated, where there isn't just one solution.

![image](https://user-images.githubusercontent.com/7494/186607370-1e657fd8-fb52-444b-bb46-f5641cccd507.png)

In the image above, the only two numbers missing in both rows and columns are 1 and 4, and it doesn't matter where I put them.

I don't know if this is OK within the sudoku domain :sweat_smile: but I personally find that to be highly unsatisfactory at the end of a solve. Hopefully this can be fixed somehow. :pray:

**Comment by jubalh** [comment]
Yeah if I remember correctly this shouldn't happen.
Do you plan to check the code and submit a PR? :)

**Comment by victorz** [comment]
Hi! Apologies for the late reply!

Uhm, I don't know. I don't really know anything about Sudoku puzzle generation, at all. I'm a programmer by trade so maybe if I study such puzzle generation I might be able to find something, but I'm really short on time these days, unfortunately.

Maybe if you drop me a link to some good info on the subject, I might look into it? _Might._ 😅

**Comment by jubalh** [comment]
No worries.

Unfortunately I don't have such link :) I would have to look for it myself.

And nudoku was a small hobby project I wrote a few years ago to play around a little. I try to maintain it as good as possible but also don't plan to put much time into it. So I don't plan to work on new features etc myself :)

**Comment by victorz** [comment]
Okay so I looked into this briefly. There is a link in the code which was your inspiration when you wrote it. That link is unfortunately dead.

I found this link though: https://www.101computing.net/sudoku-generator-algorithm/

The algorithm goes like this, copied from the page:

Our solution is based on 5 steps:

1. Generate a full grid of numbers (fully filled in). This step is more complex as it seems as we cannot just randomly generate numbers to fill in the grid. We have to make sure that these numbers are positioned on the grid following the Sudoku rules. To do so will use a sudoku solver algorithm (backtracking algorithm) that we will apply to an empty grid. We will add a random element to this solver algorithm to make sure that a new grid is generated every time we run it.
2. From our full grid, we will then remove 1 value at a time.
3. **Each time a value is removed we will apply a sudoku solver algorithm to see if the grid can still be solved and to count the number of solutions it leads to.**
4. **If the resulting grid only has one solution we can carry on the process from step 2. If not we will have to put the value we took away back in the grid.**
5. We can repeat the same process (from step 2) several times using a different value each time to try to remove additional numbers, resulting in a more difficult grid to solve. The number of attempts we will use to go through this process will have an impact on the difficulty level of the resulting grid.

I'm thinking the generator in this program is doing kind of the same thing? Please correct me if I'm wrong. I see function names like `punch_holes()` and it makes me think that's what's going on. Again, if you can recall in more detail how you did it, please correct me. :sweat_smile:

So what I'm thinking is that step 3 and 4 in the algorithm above are what is malfunctioning in this code. We are not making sure that the number of solutions to the puzzle cannot exceed 1 in the resulting puzzle. If we reach a point where the number of solutions exceed 1, we need to replace the removed value and return the puzzle (or possibly remove another value to increase difficulty, and test number of solutions again).

Do you think that could be it? If so, that could bring us closer to a fix.

**Comment by jubalh** [comment]
Ah yes, that were the steps I tried to follow.
I remember that I tried to implement in this way. And that it should always check how many solutions there are after punchin a hole.

You might be right that there is a bug in this part.
