### ISSUE TITLE
Custom color scheme

### ISSUE THREAD

**Issue by ess3sq** [jubalh/nudoku#53]
I find it taxing to maintain focus while looking at the screen for the duration of a (hard) puzzle. This is mainly due to the (not high enough) contrast between blue and green lines. Would it be possible to add configurability for the colors?

This issue has already been raised in the past #33 but has not been resolved. In that particular issue the screenshot looks fine, but try staying focused on that grid for 10-20 min and eyes do indeed start bleeding.

Therefore I kindly ask that the original response on that issue be reconsidered.

**Comment by jubalh** [comment]
> Therefore I kindly ask that the original response on that issue be reconsidered.

You could have commented on the already opened issue if this is the same problem ;)

I don't plan to implement this. But pull requests are welcome.

**Comment by ess3sq** [comment]
Very well, I think I will be working on a PR soon.

**Comment by jubalh** [comment]
Any news @ess3sq ?
