### ISSUE TITLE
Feature Request: Highlight User Input

### ISSUE THREAD

**Issue by tkiral** [jubalh/nudoku#54]
When playing, if I turn on marks, only the marks of the numbers that were provided at the start of the game are highlighted. User-added numbers are not highlighted. Could the user-added numbers be highlighted as well, or is there a reason that's not being done?

**Comment by jubalh** [comment]
The reason is that user added numbers *could* be wrong. So I decided to only highlight the ones that were added already.

**Comment by tkiral** [comment]
Probably we'd just highlight a different color or shade. I could try and work on this but it wouldn't be for a while as I'd rather spend time working on [this](https://github.com/jubalh/nudoku/issues/50) issue, and I'm not sure when I'm going to be free to sit down and work on this (plus I'm a C noob, so it'll take me a while anyways).

**Comment by jubalh** [comment]
Yeah that would be possible.
