### ISSUE TITLE
Feature Request: Earmarks

### ISSUE THREAD

**Issue by tkiral** [jubalh/nudoku#55]
On Sudoku puzzles, it's common to add earmarks to squares so as to track which values are possible for a given square. Could this be added?

**Comment by jubalh** [comment]
I would have no idea how to visualize this.

**Comment by tkiral** [comment]
We could use [sudoku.com](https://sudoku.com/) for inspiration on what exactly it'd look like (toggle "Notes" and then click any number to see).  It could mean resizing the board, as being able to see earmarks across squares simultaneously is super helpful.

If this is something you'd rather not pursue, no worries. Just thought I'd suggest it as it's something that you see a lot with Sudoku puzzles and is more helpful for the more challenging puzzles, imo.

**Comment by tkiral** [comment]
As for how users would set an earmark, my thinking was they'd enter `e#` where `#` is the number they'd like to toggle the earmark for on that square.

**Comment by jubalh** [comment]
Well I get that on HTML it is easy :)
But I'm not sure how we would display that on ncurses. Inside the cell we have only space for one character.

**Comment by tkiral** [comment]
Ah, right...

I feel like there's gotta be a way. Maybe I'll have to play around a little
