### ISSUE TITLE
Feature request: save to stream

### ISSUE THREAD

**Issue by McModknower** [jubalh/nudoku#70]
Add a commandline option similar to -p and -i that outputs a string that can be used for loading the sudoku with the -s option.

My use case is generating a few sudokus to test my code that i write to solve sudokus. Since i do that in the train on my phone in termux i don't have many sudoku implementations. I only found nudoku with pkg search.

From a first glance at the source code this looks pretty easy to do, so if you think its okay (and optionally tell me what option char to use) i can probably implement it.

**Comment by jubalh** [comment]
So you basically want the reverse of `-s` option, right?
Sounds like a nice idea. Maybe using `-o` for output would make sense. Go for it :)

**Comment by McModknower** [comment]
Bad news: my pc has a version of gettext that is too old (Version: 0.19.8.1-10build1, nudoku needs at least 0.20.0).
Good news: i can compile it in termux on my phone.

So I'm going to test the changes on my smartphone.

Is there some specific to the code style i should make sure to respect?
Also is outputting it to the stdout enough?

**Comment by jubalh** [comment]
> Is there some specific to the code style i should make sure to respect?

Try to follow what you find in the existing files.

> Also is outputting it to the stdout enough?

Yep.
